### ISSUE TITLE
Generate packages for Ubuntu 18.10 (cosmic)

### ISSUE THREAD

**Issue by buildscientist** [Stackdriver/agent-packaging#56]
Please add package support for Ubuntu 18.10 - cosmic.  Thank you.

**Comment by jkohen** [comment]
@buildscientist thank you for the suggestion. We have the support now: https://cloud.google.com/logging/docs/agent/#agent-os-list

Let us know if there is anything we can help you with.

**Comment by igorpeshansky** [comment]
This issue is for adding support in the _monitoring_ agent. At this point, the monitoring agent only supports LTS Ubuntu releases: https://cloud.google.com/monitoring/agent/#supported_operating_systems.

**Comment by jkohen** [comment]
Ah, thank you Igor, I missed that. We regularly add support for new platforms. Currently we don't have an estimate for when we will be done with this one.
